### ISSUE TITLE
 drush: not found after installing webflo/drush-shim

### ISSUE THREAD

**Issue by magick93** [webflo/drush-shim#10]
When I run `composer global require webflo/drush-shim` and then run `drush status` I get

`/bin/sh: 1: drush: not found`

**Comment by danepowell** [comment]
Do you have the composer global bin directory in your PATH? I'm surprised this isn't documented anywhere. It should probably be in the upstream composer install docs, or at least in the drush-shim readme.

Basically, find your composer global bin directory: `composer global config bin-dir --absolute`

Then add it to your PATH (such as in .bashrc): `PATH="$PATH:$HOME/.config/composer/vendor/bin"`

**Comment by magick93** [comment]
Im able to call `composer create-project ...` from any directory, so I dont think the path is the problem.

**Comment by danepowell** [comment]
The composer.phar file generally lives at a different path (`/usr/local`, `/usr/bin`, something like that). You already have that in your path, no doubt.

I'm talking about the bin directory for composer _packages_, which in general is something like `~/.config/composer/vendor/bin`

**Comment by webflo** [comment]
Merged https://github.com/webflo/drush-shim/pull/9 a few minutes ago. It recommends to use the phar file.

**Comment by webflo** [comment]
@magick93 Please use the installation instructions from the README.
