### ISSUE TITLE
Honor -r/--root options if passed

### ISSUE THREAD

**Issue by weitzman** [webflo/drush-shim#4]
many years of training and scripting have taught users to specify --root on their calls to drush. thats ignored when using this shim. seems like a bad idea to me. lets honor that if presented and if not proceed with usual DrupalFinder().

**Comment by webflo** [comment]
I think the logic is in https://github.com/drush-ops/drush/blob/c391c297cd794e7821a5d6252074388472ba5f2a/includes/startup.inc#L208 right?

**Comment by weitzman** [comment]
Yes. I think you know this, but just to be clear - drush_startup() is skipped when using drush_shim(). I think the --root handing in drush_startup() needs to be copied into drush-shim. If a root is provided, we can skip DrupalFinder. 

My hope is that Drush can rip out its Finder, Launcher and drush_locate_root() and recommend the drush-shim phar instead.

**Comment by weitzman** [comment]
This issue is still outstanding.

FYI, Drush has removed its custom Finder/Launcher scripts in favor of DrupalFinder.

**Comment by webflo** [comment]
I added this feature in 69aca666f0d7c50423fd160d8292b2018ea4c3cf and refined it in 7bf111e103d4866c22fd16d1b15df8f6d7dfbbfa

**Comment by webflo** [comment]
Try -r/-root and -d/--debug

**Comment by weitzman** [comment]
Yes, thanks. FYI --debug is supported but not -d
