### ISSUE TITLE
How to handle case when Drupal is not found

### ISSUE THREAD

**Issue by weitzman** [webflo/drush-shim#5]
Today, you can run `drush` from anywhere and get a help listing. Same for some commands like `version` and `status`. When you do this with drush-shim, you see 'Could not find Drupal in the current path.'. Share your thoughts on how we should handle this use case.

**Comment by webflo** [comment]
Either we make fallback path configurable, let the use point to an existing drush installation on their system or we ship a bundled drush.phar file?

**Comment by webflo** [comment]
@weitzman I included the current stable of drush. Please review.

**Comment by weitzman** [comment]
I don't think I like the Drush.phar solution. I'm hoping we can solve this with more elaborate help text. I wrote some text below. I think it would be great to output helpful diagnostics below the help text. I've added an example:

The Drush Launcher could not find a Drupal site to operate on, or Drush is not a dependency of your Drupal site. Navigate to anywhere inside your Drupal root directory and call this same Drush Launcher again. If you still get see this error, run `composer require drush/drush` from your project root in order to add Drush as a dependency.
```
Drush Launcher version: 1.2
Drush Launcher path: /Users/mw/.composer/vendor/bin/drush
$PATH: /foo:/bar
```

**Comment by greg-1-anderson** [comment]
Drupal Console has similar issues with its shim. I think it is important to be able to run `help` and `list` from the shim even if you do not have a Drupal site -- perhaps with a reduced list of commands. It'd be nice if the shim could `quick-drupal` all on its own.

Also, Drupal Console just made an interesting tool for finding DC plugins inside a `vendor` directory:

https://github.com/hechoendrupal/drupal-console-extend-plugin

This might be a way to provide such global commands for the shim in an extensible way. Perhaps [cgr](https://github.com/consolidation/cgr) could be enhanced to load plugins into the shim project -- presuming that the shim is installed via cgr (which I would recommend).

**Comment by weitzman** [comment]
I proposed a PR for this - #15 .

Note that the recommended install method for this shim is to wget its phar. I think thats simpler than downloading and using `cgr`.
