### ISSUE TITLE
Since drupal-finder 0.3.0, can't install anymore

### ISSUE THREAD

**Issue by jcnventura** [webflo/drush-shim#6]
composer global require webflo/drush-shim

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: webflo/drupal-finder[0.2.1, 0.3.0].
    - Can only install one of: webflo/drupal-finder[0.3.0, 0.2.1].
    - Can only install one of: webflo/drupal-finder[0.2.1, 0.3.0].
    - webflo/drush-shim 0.1.0 requires webflo/drupal-finder ^0.2.1 -> satisfiable by webflo/drupal-finder[0.2.1].
    - Installation request for webflo/drush-shim ^0.1.0 -> satisfiable by webflo/drush-shim[0.1.0].
    - Installation request for webflo/drupal-finder (locked at 0.3.0) -> satisfiable by webflo/drupal-finder[0.3.0].

**Comment by webflo** [comment]
Try to update drupal-finder.

Joao Ventura <notifications@github.com> schrieb am Mi., 14. Juni 2017,
15:28:

**Comment by webflo** [comment]
@jcnventura Does it work?

**Comment by jcnventura** [comment]
To be honest, I gave up on drush-shim, and went back to using a global installation of drush. Just thought I'd leave here an issue reporting the dependency problems.

**Comment by webflo** [comment]
I think its a problem in your global composer installation.

**Comment by jcnventura** [comment]
Well, according to the composer rules, when you specified ^0.2.1 in composer.json (which was what was there until 3 days ago), is equivalent to >=0.2.1 <0.3.0.

Since I also installed drupal/console globally, and that required 0.3.0, this package could not install..

It's probably best to specify ^0.3 instead of ^0.3.0 in this package's composer.json, so that any version 0.x of drupal-finder satisfies the composer dependency.

**Comment by webflo** [comment]
@jcnventura Ahh i got it. You are still running on drush-shim 0.1.x. Please try 0.2.x instead.
