### ISSUE TITLE
Distribute as a Phar

### ISSUE THREAD

**Issue by weitzman** [webflo/drush-shim#7]
I think it makes sense to distribute this program as a Phar and recommend that in install instructions.  I can help if this is desired.

**Comment by webflo** [comment]
We have a phar. https://github.com/webflo/drush-shim/releases/download/0.2.2/drush.phar

Its pretty big because it contains the drush.phar as fallback. The feature does not work as expected. Either we fix it or remove it.

**Comment by weitzman** [comment]
I think we should remove the embedded phar. I'll come up with a better Not
Found behavior.

**Comment by rmckeel** [comment]
@webflo @weitzman I agree, would be awesome to have PHAR installation instructions.  I'm not used to composer, followed the basic install instructions and drush is nowhere to be found / not usable even after a successful install according to composer.  However, I am used to PHAR (e.g. WP-CLI install instructions) and that may be an improved & simpler install experience.

Thanks for the great work you do!

**Comment by webflo** [comment]
@rmckeel Please review the instructions in #9

**Comment by rmckeel** [comment]
@webflo Thanks!  Got it using https://github.com/webflo/drush-shim/raw/master/phar/drush.phar.  For what it's worth, I would love for that to be 'alternate installation instructions' in the README.md file.  For now, I'll just internally document it.  Thanks!
